# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: docker compose pull # runs during prebuild
    command: docker compose up

  - init: yarn --cwd ./wordpress/themes/dev-theme
    command: yarn --cwd ./wordpress/themes/dev-theme dev

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 80
    onOpen: open-preview
  - port: 8888


vscode:
  extensions:
    - "bmewburn.vscode-intelephense-client"
    - "esbenp.prettier-vscode"