# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: docker compose pull # runs during prebuild
    command: docker compose up

  - init: yarn -cwd ./wordpress/themes/dev-theme
    command: yarn dev -cwd ./wordpress/themes/dev-theme

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
